spring:
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: localhost

logging:
  level:
    root: info

server:
  ssl:
    enabled: true
    key-store: classpath:ssl-server.jks
    key-store-password: test1234
    key-store-type: JKS
    key-alias: selfsigned_localhost_sslserver
  port: 8443